### ISSUE TITLE
Website documentation does not load

### ISSUE THREAD

**Issue by anandrajneesh** [MaxxtonGroup/microdocs#57]
I wanted to go through your getting started documentation but apart from index page nothing else loads. Is the documentation available somewhere else ?
I wanted to see how to integrate your crawlers in Spring Boot application and make things work on MicroDocs server.

**Comment by steven166** [comment]
Most of the documentation is not available on the website yet. It will be done in the near future. 

To get started, you can look at the example services how the MicroDocs crawler used: https://github.com/MaxxtonGroup/microdocs/blob/master/example/customer-service/build.gradle. 
You can start the MicroDocs server itself via Docker: docker run -d - p 3000:3000 maxxton/microdocs

**Comment by anandrajneesh** [comment]
Forgive me if this is a stupid question, can I make it work on Maven based project ?

**Comment by steven166** [comment]
Not a stupid question at all. There isn't a plugin for Maven yet. The crawler itself is based on a Doclet (a plugin for the Javadoc tool). The Gradle plugin only starts this tool. So it probably could easily be ported to Maven. So feel free to make one :)

You can also run it from the commandline:

- clone this repo: https://github.com/MaxxtonGroup/microdocs-java-plugin
- run `gradle fatjar` in the microdocs-crawler-doclet folder, this will build a fatjar in the build/libs folder
- run the javadoc tool with the following options: 
```
javadoc
-docletpath <path to the fat jar>
-doclet 'com.maxxton.microdocs.crawler.doclet.DocletRunner'
-d <output folder for the definition file>
-classpath <full classpath of you jar>
-quiet 
-projectName '<name of your project>'
-group '<group of your project>'
-version '<version of your project>
<source files>
```
See also the Javadoc documentation for information about how to use this

**Comment by steven166** [comment]
Not a supid question at all. There isn't a plugin for Maven yet. The crawler itself is based on a Doclet, like a plugin for the Javadoc tool. The Gradle plugin only starts this tool. So it probably could easily be ported to Maven. 

You can also run it from the commandline: clone the MaxxtonGroup/microdocs-java-plugin repo and run gradle fatjar in the microdocs-java-doclet

**Comment by anandrajneesh** [comment]
thanks, I'll give it a try

**Comment by robsonke** [comment]
Lets close this now.
