### ISSUE TITLE
Regex not supported in request parameters

### ISSUE THREAD

**Issue by juliansteenbakker** [MaxxtonGroup/microdocs#68]
When you add a regex to a parameter, the parameter doens't get shown in the call url.

**Example of a parameter without regex:**
![image](https://user-images.githubusercontent.com/20091319/47071014-bf811a00-d1f2-11e8-9161-678a0a7ef70c.png)

**Example of a parameter with regex:**
![image](https://user-images.githubusercontent.com/20091319/47071064-db84bb80-d1f2-11e8-9917-845c38a2b11d.png)

Regex used: {reservationId:[1-9]\d*}

**EXPECTED RESULTS:**
Show it like: /api/v1/reservations/{reservationId}/snapshots/criteria/{snapshotCriteriaId}

**Comment by robsonke** [comment]
Since this is breaking the Swagger api specs too, I'm fixing it. It seems to wrong in the Java scraper, as the microdocs spec doesn't contain it either.

**Comment by juliansteenbakker** [comment]
> Since this is breaking the Swagger api specs too, I'm fixing it. It seems to wrong in the Java scraper, as the microdocs spec doesn't contain it either.

Thanks for the quick response 😆

PS, The NAS you gave me is still going strong! Goed weekend toegewenst.

**Comment by robsonke** [comment]
Haha cool, by accident i faced the same issue today

**Comment by robsonke** [comment]
See https://github.com/MaxxtonGroup/microdocs-java-plugin/pull/15
