### ISSUE TITLE
MicroDocs Server answers request with 400 Bad Request

### ISSUE THREAD

**Issue by FrederikSchlemmer** [MaxxtonGroup/microdocs#69]
When using the microdocs server with the docker command:
`docker run --name microdocs -v /some/data/folder:/microdocs/microdocs-server/data -p 3000:3000 -d maxxton/microdocs`

After including the Gradle Plugin Version 1.9.6 in the buildscript:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("com.maxxton:microdocs-crawler-gradle:1.9.6")
    }
}
```

and running the command `publishMicroDocs`. 

I get the error "400 - Bad Request". Unfortunately there is no exact API definition, so I can't check the format. Can you help me with the problem?

**Comment by steven166** [comment]
Could you share your microdocs.json file in build/reports?

**Comment by FrederikSchlemmer** [comment]
Of course I do. I've already taken a look inside.

`{
  "info": {
    "title": "GitStalkerDataPull",
    "version": "1.0"
  },
  "paths": {
    "/organizationdetail/{organizationName}": {
      "get": {
        "controller": {
          "$ref": "#/components/OrganizationController"
        },
        "method": {
          "$ref": "#/components/OrganizationController/methods/retrieveOrganizationDetail(String)"
        },
        "description": "Interface for the OrganizationDetail object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
        "operationId": "retrieveOrganizationDetail",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Transferred organization name",
            "required": true,
            "name": "organizationName",
            "in": "path"
          }
        ],
        "responses": {
          "default": {
            "description": "Replies either with the data, various errors or processing information",
            "schema": {
              "type": "object",
              "name": "Object"
            }
          }
        }
      }
    },
    "/members/{organizationName}": {
      "get": {
        "controller": {
          "$ref": "#/components/OrganizationController"
        },
        "method": {
          "$ref": "#/components/OrganizationController/methods/retrieveOrganizationMembers(String)"
        },
        "description": "Interface for the Organization members object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
        "operationId": "retrieveOrganizationMembers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Transferred organization name",
            "required": true,
            "name": "organizationName",
            "in": "path"
          }
        ],
        "responses": {
          "default": {
            "description": "Replies either with the data, various errors or processing information",
            "schema": {
              "type": "object",
              "name": "Object"
            }
          }
        }
      }
    },
    "/createdreposbymembers/{organizationName}": {
      "get": {
        "controller": {
          "$ref": "#/components/OrganizationController"
        },
        "method": {
          "$ref": "#/components/OrganizationController/methods/retrieveCreatedReposByOrganizationMembers(String)"
        },
        "description": "Interface for the Created Repo by organisation members object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
        "operationId": "retrieveCreatedReposByOrganizationMembers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Transferred organization name",
            "required": true,
            "name": "organizationName",
            "in": "path"
          }
        ],
        "responses": {
          "default": {
            "description": "Replies either with the data, various errors or processing information",
            "schema": {
              "type": "object",
              "name": "Object"
            }
          }
        }
      }
    },
    "/teams/{organizationName}": {
      "get": {
        "controller": {
          "$ref": "#/components/OrganizationController"
        },
        "method": {
          "$ref": "#/components/OrganizationController/methods/retrieveOrganizationTeams(String)"
        },
        "description": "Interface for the Organization teams object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
        "operationId": "retrieveOrganizationTeams",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Transferred organization name",
            "required": true,
            "name": "organizationName",
            "in": "path"
          }
        ],
        "responses": {
          "default": {
            "description": "Replies either with the data, various errors or processing information",
            "schema": {
              "type": "object",
              "name": "Object"
            }
          }
        }
      }
    },
    "/repositories/{organizationName}": {
      "get": {
        "controller": {
          "$ref": "#/components/OrganizationController"
        },
        "method": {
          "$ref": "#/components/OrganizationController/methods/retrieveOrganizationRepositories(String)"
        },
        "description": "Interface for the Organization repositories object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
        "operationId": "retrieveOrganizationRepositories",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Transferred organization name",
            "required": true,
            "name": "organizationName",
            "in": "path"
          }
        ],
        "responses": {
          "default": {
            "description": "Replies either with the data, various errors or processing information",
            "schema": {
              "type": "object",
              "name": "Object"
            }
          }
        }
      }
    },
    "/externalrepositories/{organizationName}": {
      "get": {
        "controller": {
          "$ref": "#/components/OrganizationController"
        },
        "method": {
          "$ref": "#/components/OrganizationController/methods/retrieveExternalRepositories(String)"
        },
        "description": "Interface for the Organization repositories object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
        "operationId": "retrieveExternalRepositories",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Transferred organization name",
            "required": true,
            "name": "organizationName",
            "in": "path"
          }
        ],
        "responses": {
          "default": {
            "description": "Replies either with the data, various errors or processing information",
            "schema": {
              "type": "object",
              "name": "Object"
            }
          }
        }
      }
    },
    "/**": {
      "get": {
        "controller": {
          "$ref": "#/components/OrganizationController"
        },
        "method": {
          "$ref": "#/components/OrganizationController/methods/response404Error()"
        },
        "description": "Interface for the remaining requests so that mapping errors are not displayed.",
        "operationId": "response404Error",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "default": {
            "description": "404 Error",
            "schema": {
              "type": "object",
              "name": "Object"
            }
          }
        }
      }
    }
  },
  "components": {
    "MemberPRProcessor": {
      "name": "de.adesso.gitstalker.core.processors.MemberPRProcessor",
      "type": "service",
      "file": "de/adesso/gitstalker/core/processors/MemberPRProcessor.java",
      "description": "",
      "authors": [],
      "annotations": {
        "Service": {}
      },
      "methods": {
        "generateRequestsBasedOnMemberPR()": {
          "name": "generateRequestsBasedOnMemberPR",
          "description": "Generates the following requests after the MemberPR requests are all processed. Saves the generated requests in the repository.",
          "lineNumber": 82
        },
        "processQueryResponse(Data)": {
          "name": "processQueryResponse",
          "description": "Processes the response from the requests",
          "parameters": [
            "Data"
          ],
          "lineNumber": 102
        },
        "processRequestForRemainingInformation(PageInfo,String)": {
          "name": "processRequestForRemainingInformation",
          "description": "Creates the subsequent requests if it becomes clear during processing that information is still open in the section.\n If finished the amount of external contributions is calculated and new requests are generated.",
          "parameters": [
            "PageInfo",
            "String"
          ],
          "lineNumber": 59
        },
        "processResponse(Query)": {
          "name": "processResponse",
          "description": "Response processing of the MemberPR request. Processing through every MemberPRRepoID and save it in a ArrayList.\n Creating a MemberPR object containing the MemberPRRepoID ArrayList and the PageInfo wrapped into the ResponseWrapper.",
          "parameters": [
            "Query"
          ],
          "lineNumber": 42
        },
        "checkIfPullRequestIsActiveSinceOneYear(Date)": {
          "name": "checkIfPullRequestIsActiveSinceOneYear",
          "description": "Checks if the selected updatedDate is within one year.",
          "parameters": [
            "Date"
          ],
          "lineNumber": 136
        },
        "processNumOfExternalRepoContributions()": {
          "name": "processNumOfExternalRepoContributions",
          "description": "Calculates the amount of external contributions and saves it in the organization",
          "lineNumber": 74
        }
      }
    },
    "OrganizationController": {
      "name": "de.adesso.gitstalker.core.REST.OrganizationController",
      "type": "controller",
      "file": "de/adesso/gitstalker/core/REST/OrganizationController.java",
      "description": "",
      "authors": [],
      "annotations": {
        "CrossOrigin": {},
        "RestController": {}
      },
      "methods": {
        "handleProcessingOrganizationException(ProcessingOrganizationException)": {
          "name": "handleProcessingOrganizationException",
          "description": "Exception handler for an still processing organization.",
          "parameters": [
            "ProcessingOrganizationException"
          ],
          "lineNumber": 251
        },
        "retrieveOrganizationRepositories(String)": {
          "name": "retrieveOrganizationRepositories",
          "description": "Interface for the Organization repositories object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
          "parameters": [
            "String"
          ],
          "lineNumber": 85
        },
        "checkStatusOfRequestedInformation(String)": {
          "name": "checkStatusOfRequestedInformation",
          "description": "Method used to check if there is already requested information available.\n If there are no requests running for the requested organization then the requests are generated, after validating if the transferred organization is valid.",
          "parameters": [
            "String"
          ],
          "lineNumber": 263
        },
        "retrieveCreatedReposByOrganizationMembers(String)": {
          "name": "retrieveCreatedReposByOrganizationMembers",
          "description": "Interface for the Created Repo by organisation members object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
          "parameters": [
            "String"
          ],
          "lineNumber": 130
        },
        "retrieveOrganizationMembers(String)": {
          "name": "retrieveOrganizationMembers",
          "description": "Interface for the Organization members object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
          "parameters": [
            "String"
          ],
          "lineNumber": 70
        },
        "handleInvalidGithubAPITokenException(InvalidGithubAPITokenException)": {
          "name": "handleInvalidGithubAPITokenException",
          "description": "Exception handler for an invalid Github API token.",
          "parameters": [
            "InvalidGithubAPITokenException"
          ],
          "lineNumber": 223
        },
        "retrieveOrganizationTeams(String)": {
          "name": "retrieveOrganizationTeams",
          "description": "Interface for the Organization teams object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
          "parameters": [
            "String"
          ],
          "lineNumber": 115
        },
        "handleNoRemainingRateLimitException(NoRemainingRateLimitException)": {
          "name": "handleNoRemainingRateLimitException",
          "description": "Exception handler for an invalid Github API token.",
          "parameters": [
            "NoRemainingRateLimitException"
          ],
          "lineNumber": 209
        },
        "validateOrganization(ProcessingInformationProcessor)": {
          "name": "validateOrganization",
          "description": "Method to validate the organization.\n If the transferred organization name is valid the processing is started by creating a ProcessingOrganization object and saving the validation query for processing. Then the methods return the HttpStatus 102 - Processing.\n If the transferred organization name is invalid the HttpStatus 400 - Bad Request is returned.",
          "parameters": [
            "ProcessingInformationProcessor"
          ],
          "lineNumber": 295
        },
        "retrieveOrganizationDetail(String)": {
          "name": "retrieveOrganizationDetail",
          "description": "Interface for the OrganizationDetail object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
          "parameters": [
            "String"
          ],
          "lineNumber": 55
        },
        "retrieveExternalRepositories(String)": {
          "name": "retrieveExternalRepositories",
          "description": "Interface for the Organization repositories object. Checks the current status of the queries for the relevant organization and provides an appropriate response.",
          "parameters": [
            "String"
          ],
          "lineNumber": 100
        },
        "processResponseEntity(RequestType,String,HttpStatus)": {
          "name": "processResponseEntity",
          "description": "Processes the response using the request type and the HTTP status.",
          "parameters": [
            "RequestType",
            "String",
            "HttpStatus"
          ],
          "lineNumber": 155
        },
        "handleInvalidOrganizationNameRequestException(InvalidOrganizationNameRequestException)": {
          "name": "handleInvalidOrganizationNameRequestException",
          "description": "Exception handler for an invalid organization name in request.",
          "parameters": [
            "InvalidOrganizationNameRequestException"
          ],
          "lineNumber": 237
        },
        "formatInput(String)": {
          "name": "formatInput",
          "description": "",
          "parameters": [
            "String"
          ],
          "lineNumber": 308
        },
        "response404Error()": {
          "name": "response404Error",
          "description": "Interface for the remaining requests so that mapping errors are not displayed.",
          "lineNumber": 141
        }
      }
    },
    "MemberGrowthChartJSParser": {
      "name": "de.adesso.gitstalker.core.parser.MemberGrowthChartJSParser",
      "type": "service",
      "file": "de/adesso/gitstalker/core/parser/MemberGrowthChartJSParser.java",
      "description": "",
      "authors": [],
      "annotations": {
        "NoArgsConstructor": {},
        "Service": {}
      },
      "methods": {
        "convertStringBackToDate(String)": {
          "name": "convertStringBackToDate",
          "description": "",
          "parameters": [
            "String"
          ],
          "lineNumber": 34
        },
        "getFormattedDate(Date)": {
          "name": "getFormattedDate",
          "description": "",
          "parameters": [
            "Date"
          ],
          "lineNumber": 42
        },
        "parseInputToChartJSData(LinkedHashMap)": {
          "name": "parseInputToChartJSData",
          "description": "",
          "parameters": [
            "LinkedHashMap"
          ],
          "lineNumber": 20
        }
      }
    },
    "RepositoryProcessor": {
      "name": "de.adesso.gitstalker.core.processors.RepositoryProcessor",
      "type": "service",
      "file": "de/adesso/gitstalker/core/processors/RepositoryProcessor.java",
      "description": "",
      "authors": [],
      "annotations": {
        "Service": {}
      },
      "methods": {
        "getDescription(NodesRepositories)": {
          "name": "getDescription",
          "description": "",
          "parameters": [
            "NodesRepositories"
          ],
          "lineNumber": 124
        },
        "processRequestForRemainingInformation(PageInfo,String)": {
          "name": "processRequestForRemainingInformation",
          "description": "Creates the subsequent requests if it becomes clear during processing that information is still open in the section.\n If finished the repositories are added to the organization.",
          "parameters": [
            "PageInfo",
            "String"
          ],
          "lineNumber": 60
        },
        "getProgrammingLanguage(NodesRepositories)": {
          "name": "getProgrammingLanguage",
          "description": "",
          "parameters": [
            "NodesRepositories"
          ],
          "lineNumber": 119
        },
        "processResponse(Query)": {
          "name": "processResponse",
          "description": "Performs the complete processing of an answer.",
          "parameters": [
            "Query"
          ],
          "lineNumber": 44
        },
        "processQueryResponse(Repositories)": {
          "name": "processQueryResponse",
          "description": "Processes the response of the requests.",
          "parameters": [
            "Repositories"
          ],
          "lineNumber": 73
        },
        "getLicense(NodesRepositories)": {
          "name": "getLicense",
          "description": "",
          "parameters": [
            "NodesRepositories"
          ],
          "lineNumber": 114
        }
      }
    },
    "TeamProcessor": {
      "name": "de.adesso.gitstalker.core.processors.TeamProcessor",
      "type": "service",
      "file": "de/adesso/gitstalker/core/processors/TeamProcessor.java",
      "description": "",
      "authors": [],
      "annotations": {
        "Service": {}
      },
      "methods": {
        "processQueryResponse(Teams)": {
          "name": "processQueryResponse",
          "description": "Processing the response from the TeamRequest. Creation of the team objects and saving in the HashMap.",
          "parameters": [
            "Teams"
          ],
          "lineNumber": 75
        },
        "processRequestForRemainingInformation(PageInfo,String)": {
          "name": "processRequestForRemainingInformation",
          "description": "Processing if additional requests are necessary for outstanding information. Otherwise the collected data will be added to the organization.",
          "parameters": [
            "PageInfo",
            "String"
          ],
          "lineNumber": 61
        },
        "processResponse(Query)": {
          "name": "processResponse",
          "description": "Processing TeamRequest response.\n Update of the RateLimit from the Github API. Check whether it is the last request of the type.",
          "parameters": [
            "Query"
          ],
          "lineNumber": 45
        },
        "processTeamMembers(ArrayList)": {
          "name": "processTeamMembers",
          "description": "Processing of the members of the teams and selection of the suitable member object from the organization.",
          "parameters": [
            "ArrayList"
          ],
          "lineNumber": 88
        },
        "processTeamRepositories(ArrayList)": {
          "name": "processTeamRepositories",
          "description": "Processing of the repositories of the teams and selection of the suitable repository object from the organization.",
          "parameters": [
            "ArrayList"
          ],
          "lineNumber": 104
        }
      }
    },
    "OrganizationValidationProcessor": {
      "name": "de.adesso.gitstalker.core.processors.OrganizationValidationProcessor",
      "type": "service",
      "file": "de/adesso/gitstalker/core/processors/OrganizationValidationProcessor.java",
      "description": "",
      "authors": [],
      "annotations": {
        "Service": {}
      },
      "methods": {
        "generateOrganizationWrapper(String)": {
          "name": "generateOrganizationWrapper",
          "description": "Generates an organization wrapper object if the organization isn't assigned already.",
          "parameters": [
            "String"
          ],
          "lineNumber": 58
        },
        "processResponse(Query)": {
          "name": "processResponse",
          "description": "Performs the complete processing of an answer.",
          "parameters": [
            "Query"
          ],
          "lineNumber": 39
        }
      }
    },
    "ResponseProcessorService": {
      "name": "de.adesso.gitstalker.core.processors.ResponseProcessorService",
      "type": "service",
      "file": "de/adesso/gitstalker/core/processors/ResponseProcessorService.java",
      "description": "This is the Response manager that carries the different processors within itself.",
      "authors": [],
      "annotations": {
        "Service": {}
      },
      "methods": {
        "processResponse(Query)": {
          "name": "processResponse",
          "description": "The central routing of requests to processors is controlled here.",
          "parameters": [
            "Query"
          ],
          "lineNumber": 49
        }
      }
    },
    "OrganizationDetailProcessor": {
      "name": "de.adesso.gitstalker.core.processors.OrganizationDetailProcessor",
      "type": "component",
      "file": "de/adesso/gitstalker/core/processors/OrganizationDetailProcessor.java",
      "description": "",
      "authors": [],
      "annotations": {
        "Component": {}
      },
      "methods": {
        "processQueryResponse(Data)": {
          "name": "processQueryResponse",
          "description": "Processes the response of the requests.",
          "parameters": [
            "Data"
          ],
          "lineNumber": 59
        },
        "processResponse(Query)": {
          "name": "processResponse",
          "description": "Performs the complete processing of an answer.",
          "parameters": [
            "Query"
          ],
          "lineNumber": 45
        }
      }
    },
    "Application": {
      "name": "de.adesso.gitstalker.Application",
      "type": "application",
      "file": "de/adesso/gitstalker/Application.java",
      "description": "",
      "authors": [],
      "annotations": {
        "SpringBootApplication": {},
        "EnableScheduling": {},
        "EnableMongoRepositories": {
          "properties": {
            "value": "com.maxxton.microdocs.core.reflect.ReflectAnnotationValue@478db956"
          }
        },
        "ComponentScan": {
          "properties": {
            "basePackages": "com.maxxton.microdocs.core.reflect.ReflectAnnotationValue@6ca18a14"
          }
        }
      },
      "methods": {
        "responseProcessorTask()": {
          "name": "responseProcessorTask",
          "description": "Initialization of the Response Task for processing the request response data of the queries.",
          "lineNumber": 49
        },
        "organisationUpdateTask()": {
          "name": "organisationUpdateTask",
          "description": "Initialization of the Update Task for the saved organisation",
          "lineNumber": 29
        },
        "requestProcessorTask()": {
          "name": "requestProcessorTask",
          "description": "Initialization of the Request Task for crawling the data according to the saved queries.",
          "lineNumber": 39
        }
      }
    }
  }
}`

**Comment by steven166** [comment]
I think you're missing the "group" property.
Could you add this to your build.gradle file:
```
buildMicroDocs {
  options.addStringOption("group", 'my-group-name');
}
```

**Comment by FrederikSchlemmer** [comment]
Thank you so much it worked!
